# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 20:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('help_text', models.TextField(verbose_name='help text')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='extent')),
                ('active', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326, verbose_name='geometry')),
                ('status', models.CharField(default='new', max_length=10)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('challenge', models.ForeignKey(db_column='challenge_slug', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maproulette.Challenge')),
            ],
        ),
    ]
