# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 23:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='geometry')),
            ],
        ),
    ]
