# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 05:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maproulette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('help_text', models.TextField(verbose_name='help text')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='extent')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
        migrations.AddField(
            model_name='task',
            name='identifier',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326, verbose_name='geometry'),
        ),
        migrations.AddField(
            model_name='task',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='maproulette.Challenge'),
            preserve_default=False,
        ),
    ]
