# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maproulette', '0005_auto_20151205_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='challenge',
            field=models.ForeignKey(db_column='challenge_slug', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maproulette.Challenge'),
        ),
    ]
